Fix type mismatches exposed by JSCompiler performance change in union type builder which makes union building more conservative:
  javascript/closure/fs/error.js:69: ERROR - assignment to property code of goog.fs.Error
  found   : number
  required: goog.fs.Error.ErrorCode<number>
      this.code = goog.asserts.assertNumber(error.code);
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  javascript/closure/fs/error.js:70: ERROR - actual parameter 1 of goog.fs.Error.getNameFromCode_ does not match formal parameter
  found   : number
  required: (goog.fs.Error.ErrorCode<number>|undefined)
      this.name = goog.fs.Error.getNameFromCode_(error.code);
                                                 ^^^^^^^^^^

RELNOTES:n/a

RELNOTES=n/a

-------------
Created by MOE: https://github.com/google/moe
MOE_MIGRATED_REVID=242170094