Workaround for Compiler error
~3 days ago, compiling closure library began throwing this error with the external head compiler: ./closure/goog/test_module.js:25: ERROR - required "goog.test_module_dep" namespace never provided
goog.require('goog.test_module_dep');