Rollforward now that tests are fixed
*** Original change description ***

Automated g4 rollback of changelist 234190091.

*** Reason for rollback ***

This change breaks at tests

*** Original change:

Add better type information to selectionHandler_ (matching the rest of the file).

When compiling this file in isolation, I was getting:

javascript/closure/ui/ac/autocomplete.js:646: ERROR - Property selectRow never defined on Object
    var suppressUpdate = this.selectionHandler_.selectRow(selectedRow);
                                                ^^^^^^^^^

RELNOTES: na

***

-------------
Created by MOE: https://github.com/google/moe
MOE_MIGRATED_REVID=236665350