Fixed closure compiler errors and warnings.
./closure/goog/datasource/expr.js:276: ERROR - missing require: 'goog.ds.DataManager'

                                  goog.ds.DataManager.getInstance();

                                  ^

./closure/goog/graphics/vmlelement.js:116: ERROR - missing require: 'goog.graphics.VmlGraphics'

      goog.graphics.VmlGraphics.toSizeCoord(height);

      ^

./closure/goog/graphics/vmlelement.js:276: ERROR - missing require: 'goog.graphics.VmlGraphics'

  style.height = goog.graphics.VmlGraphics.toSizePx(height);

                 ^

./closure/goog/graphics/vmlelement.js:421: ERROR - missing require: 'goog.graphics.VmlGraphics'

  style.height = goog.graphics.VmlGraphics.toPosPx(height);

closure/goog/ui/tree/basenode.js:1298: WARNING - @suppress annotation not allowed here. See https://github.com/google/closure-compiler/wiki/@suppress-annotations

goog.ui.tree.BaseNode.prototype.onClick_ = goog.events.Event.preventDefault;

^

closure/goog/ui/tree/basenode.js:1298: WARNING - Property onClick_ must be marked @private

goog.ui.tree.BaseNode.prototype.onClick_ = goog.events.Event.preventDefault;

^