Automated g4 rollback of changelist 234190091.
*** Reason for rollback ***

This change breaks at least two critical tools for YouTube admin.

I don't fully understand *why* this breaks the autocomplete-selection for us, but it looks like it's related to us passing the same instance as both matcher and selection handler to the constructor.

Bugs:
Engineering bug to track troubleshooting: b/125005799
User reported bugs of tools that break: b/124878373, b/124672945, b/124614601

*** Original change description ***

Add better type information to selectionHandler_ (matching the rest of the file).

When compiling this file in isolation, I was getting:

javascript/closure/ui/ac/autocomplete.js:646: ERROR - Property selectRow never defined on Object
    var suppressUpdate = this.selectionHandler_.selectRow(selectedRow);
                                                ^^^^^^^^^

RELNOTES: na

***

-------------
Created by MOE: https://github.com/google/moe
MOE_MIGRATED_REVID=235017724