Change types in Closure to avoid property accesses on *, which the new type inference warns about. Switched to ? since there isn't really a useful, more specific type.
Sample warning:
uri/uri.js:1294: ERROR - JSC_NTI_PROPERTY_ACCESS_ON_NONOBJECT - Cannot access property length of non-object type *.
    for (var j = 0; j < val.length; j++) {
                        ^

RELNOTES:n/a
-------------
Created by MOE: https://github.com/google/moe
MOE_MIGRATED_REVID=113444757