Add var for extraRequire
works around compiler error:

```
compiler: ./closure/goog/test_module.js:25: ERROR - required "goog.test_module_dep" namespace never provided
goog.require('goog.test_module_dep');
```