Automated g4 rollback of changelist 245453963.
*** Reason for rollback ***

Roll forward of cl/243685265 (32ef85e41) (32ef85e41): Update isValidShortcut_ to support shadow dom event.

NEW: Fix "TypeError: e.composedPath is not a function" for older Firefox

RELNOTES: n/a

*** Original change description ***

Automated g4 rollback of changelist 244201668.

*** Reason for rollback ***

b/131412663

*** Original change description ***

Automated g4 rollback of changelist 243739896.

*** Reason for rollback ***

Roll forward of cl/243685265 (32ef85e41) (32ef85e41): Update isValidShortcut_ to support shadow dom event.

NEW: Fixed event.getBrowserEvent is not a function.

RELNOTES: n/a

*** Original change description ***

Automated g4 rollback of changelist 243685265.

*** Reason for rollback ***

Causing breakage: https://test...

***

-------------
Created by MOE: https://github.com/google/moe
MOE_MIGRATED_REVID=246330780