goog.require InputLabel in InputDatePicker
Context: I included InputDatePicker in cl/91828653 and got the following error:

javascript/closure/ui/inputdatepicker.js:164: ERROR - Bad type annotation. Unknown type goog.ui.LabelInput
    var labelInput = /** @type {goog.ui.LabelInput} */ (el.labelInput_);
-------------
Created by MOE: http://code.google.com/p/moe-java
MOE_MIGRATED_REVID=92181260